import type { MetadataRoute } from "next";

// Served at /manifest.webmanifest. Colours are P1 placeholders — Prompt 5 sets
// them from the extracted prototype tokens. Icons are placeholder solids until
// the branded icon set lands (generated by scripts/generate-icons.mjs).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "AriyaPlanner",
    short_name: "AriyaPlanner",
    description:
      "Plan Nigerian weddings, burials, birthdays and naming ceremonies — culturally correct programmes, naira budgets, committee coordination and a day-of command centre.",
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#FBF7F0", // placeholder cream — P5 replaces
    theme_color: "#0B6B3A", // placeholder emerald — P5 replaces
    categories: ["lifestyle", "productivity"],
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-192-maskable.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-512-maskable.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
